version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime
  kafka:
    #    build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #      KAFKA_ADVERTISED_HOST_NAME: 10.44.31.125
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.44.31.125:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - /etc/localtime:/etc/localtime
#docker run -d  -p 9000:9000  -e KAFKA_BROKERCONNECT=10.44.31.125:9092  -e JVM_OPTS="-Xms32M -Xmx64M"  -e SERVER_SERVLET_CONTEXTPATH="/"  obsidiandynamics/kafdrop:latest